Add Android debug steps

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -11,6 +11,22 @@ jobs:
     timeout-minutes: 30
 
     steps:
+
+    - name: Debug Android
+      run: |
+        echo "===== Environment Variables ====="
+        env | grep ANDROID
+        echo "\n===== Installed Tools ====="
+        which sdkmanager || echo "sdkmanager not found"
+
+    - name: Pre-check Android SDK
+      run: |
+        echo "ANDROID_HOME: $ANDROID_HOME"
+        if [ ! -d "$ANDROID_HOME" ]; then
+          echo "::error::ANDROID_HOME not set!"
+          exit 1
+        fi  
+
     - uses: actions/checkout@v4
 
     - name: Set up Python
